terraform:
  - any: [ "*.tf", "infraestructure/terraform/**" ]

workflow:
  - any: [ ".github/workflows/*" ]

code:
  - any: [ "src/main/python/**" ]

test:
  - any: [ "src/test/python/**", "src/test/**" ]