---
name: "Terraform"

"on":
  push:
    branches: [ main, develop ]
  workflow_call:
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS:
        description: 'GCP CI/CD Service Account'
        required: true

jobs:
  terraform-plan-test:
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: test
    env:
      working-directory: infraestructure/terraform/de-challengue-test
    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Check out code
        uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.2

      - name: Terraform Fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform init
        id: init
        run: terraform init
        working-directory: ${{ env.working-directory }}
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          TF_LOG: TRACE

      - name: Terraform validate
        id: validate
        run: terraform validate
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Terraform plan
        id: plan
        run: terraform plan
        working-directory: ${{ env.working-directory }}
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

#      - name: Terraform apply
#        id: apply
#        run: terraform apply -auto-approve -input=false
#        working-directory: ${{ env.working-directory }}
#        env:
#          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}


  terraform-plan-prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: prod

    env:
      working-directory: infraestructure/terraform/de-challenge
    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Check out code
        uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.2

      - name: Terraform Fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Echo files
        run: ls
        working-directory: ${{ env.working-directory }}

      - name: Terraform init
        id: init
        run: terraform init
        working-directory: ${{ env.working-directory }}

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color
        working-directory: ${{ env.working-directory }}

#      - name: Terraform apply
#        id: apply
#        run: terraform apply -auto-approve -input=false
#        working-directory: ${{ env.working-directory }}