---
name: "Code & Artifacts deployment"

"on":
  push:
    branches:
      - main
  workflow_call:
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS:
        description: 'GCP CI/CD Service Account'
        required: true
  workflow_dispatch:

env:
  GCP_PROJECT_ID: de-challenge-336404
  ARTIFACTS_BUCKET: de-challenge-336404-artifacts


jobs:
  workflows-deployment:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: 'Check gcloud CLI'
        run: 'gcloud info'
      - name: 'Deploy of consoles_dim'
        run: gcloud workflows deploy consoles_dim --source=src/main/workflows/consoles_dim.yml
      - name: 'Deploy of metacritic'
        run: gcloud workflows deploy metacritic --source=src/main/workflows/metacritic.yml
      - name: 'Deploy of undefined_files'
        run: gcloud workflows deploy undefined_files --source=src/main/workflows/undefined_files.yml

  workflows-trigger-gcf-deployment:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: 'Check gcloud CLI'
        run: 'gcloud info'
      - name: 'Copy infra file'
        run: 'cp src/resources/infra.ini src/main/python/google_cloud_functions/workflow_trigger/'
      - name: 'Deploy of Workflow trigger GCF'
        run: |
          gcloud functions deploy workflow_trigger \
            --entry-point main \
            --runtime python37 \
            --trigger-topic=lnd-notification \
            --source=src/main/python/google_cloud_functions/workflow_trigger/ \
            --clear-max-instances \
            --region us-central1 \
            --memory 128MB \
            --set-env-vars ENVIRONMENT=PROD

  dataflow-flex-tmpl-deployment:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: 'Check gcloud CLI'
        run: 'gcloud info'

      - name: 'Deploy of Dataflow Template to Container Registry'
        run: gcloud builds submit --tag "${{ env.TEMPLATE_IMAGE }}" .
        env:
          TEMPLATE_IMAGE: gcr.io/${{ env.GCP_PROJECT_ID }}/dataflow/result_csv:latest
        working-directory: src/main/python/dataflow/result_csv

      - name: 'Save Dataflow Template to GCS'
        run: |
          gcloud dataflow flex-template build ${{ env.TEMPLATE_PATH }} \
            --image "${{ env.TEMPLATE_IMAGE }}" --sdk-language "PYTHON" \
            --metadata-file "src/main/python/dataflow/result_csv/metadata.json"
        env:
          TEMPLATE_PATH: gs://${{ env.ARTIFACTS_BUCKET }}/dataflow_templates/result_csv.json
          TEMPLATE_IMAGE: gcr.io/${{ env.GCP_PROJECT_ID }}/dataflow/result_csv:latest
